# Generated by Django 4.2.4 on 2023-08-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertopic',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='usertopic',
            name='user',
        ),
        migrations.AlterField(
            model_name='article',
            name='topics',
            field=models.ManyToManyField(to='topics.topic'),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='UserTopic',
        ),
    ]
